#1. Name our workflow
name: demoflow 

#2. Specify a trigger
on: 
  push:
    branches:
      - master

#3. Specify the job to be executed and the steps to execute that job
jobs:
  #a. Give our job a name
  run-test:

  #b. SPecify the operating System our job should run on
  runs-on: ubuntu-latest
  
  # c. Define the steps to execute our job
  steps:

    #Check out the source code that was just pushed to the specified branch (e.g.master)
    - name: Check out our example code
      uses: actions/chechout@v2

      #install NOde
      - name: Set up Node.JS
        uses: action/setup-node@v1
        with:
          node-version: 10.x
          #Run the test
          - name: Run tests
             run: |
               npm i
               npm test